// src/pages/About.jsx
import React from "react";

const About = () => {
  return (
    <div className="h-screen w-screen flex items-center justify-center">
      <div>
        <h1 className="text-3xl text-center">About Us</h1>
        <p className="text-center">
          This is the about page.
        </p>
      </div>
    </div>
  );
};

export default About;

// src/views/About.vue
<template>
  <div class="about">
    <h1>About Us</h1>
    <p>This is the about page.</p>
  </div>
</template>

<script>
export default {
  name: 'About',
};
</script>

<style scoped>
.about {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
}
</style>
