// src/pages/Contact.jsx
import React from "react";

const Contact = () => {
  return (
    <div className="h-screen w-screen flex items-center justify-center">
      <div>
        <h1 className="text-3xl text-center">Contact Us</h1>
        <p className="text-center">
          This is the contact page.
        </p>
      </div>
    </div>
  );
};

export default Contact;

// src/views/Contact.vue
<template>
  <div class="contact">
    <h1>Contact Us</h1>
    <p>This is the contact page.</p>
  </div>
</template>

<script>
export default {
  name: 'Contact',
};
</script>

<style scoped>
.contact {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
}
</style>
